
<!-- saved from url=(0079)http://www.unf.edu/public/cop4620/ree/Examples/LEXYACC_sample/SimpCalc/makefile -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><div id="StayFocusd-infobar" style="display:none;"><img src="chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/img/eye_19x19_red.png"><span id="StayFocusd-infobar-msg"></span><span id="StayFocusd-infobar-links"><a href="http://www.unf.edu/public/cop4620/ree/Examples/LEXYACC_sample/SimpCalc/makefile#" id="StayFocusd-infobar-never-show">hide forever</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="http://www.unf.edu/public/cop4620/ree/Examples/LEXYACC_sample/SimpCalc/makefile#" id="StayFocusd-infobar-hide">hide once</a></span></div><pre style="word-wrap: break-word; white-space: pre-wrap;">p58: p58.tab.c lex.yy.c
	cc -o p58 p58.tab.c lex.yy.c 

p58.tab.c: p58.y
	bison -d p58.y

lex.yy.c: p58.l
	lex p58.l
</pre></body></html>